---
config:
  name: test
  processors_per_node: 1
  trace_file: trace.prv
  time_offset_fudge_factor: 0
  input:
    ibnetdiscover_file: ibnetdiscover.out
    ranktohost_file: ranktohost.csv
    fdbs_file: ibdiagnet.fdbs
