#!/bin/sh

cd $(dirname $0)

clean=0
if [[ "$1" == "--clean" ]]; then
	clean=1
	shift
fi

if [[ "$#" -eq 0 ]]; then
	TESTS=*.test
else
	TESTS="$@"
fi

if [[ "${clean}" -eq 1 ]]; then
	rm -rf work
fi

[[ ! -d work ]] && mkdir -p work
cp -pPR lib work/

opp_test gen $TESTS || exit 1
pushd work
opp_makemake -f -I../../src -L../../src -lib_flit_sim --deep \
	--no-deep-includes || exit 1
make || exit 1
popd
NEDPATH=.:../../../src opp_test run -v -p ib_model $TESTS
